apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: bzFleXdoOWg=
  CLOUDINARY_KEY: NzYyNzgxODgxMzMzMzI2
  CLOUDINARY_SECRET: KioqKioqKioqKg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM1p5WldSa2VUa3hNakFpTENKaElqb2lZMjF6WW1veGMzZzJNR3R0TlRNd2N6VmlZV0UwY2pZd09TSjkueExqRzNCSkVkdzVBSktIa2ZqanMyQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9rdXBwaXJlZGR5dmVua2F0ZXN3YXJhcmVkZHk2OV9kYl91c2VyOnJwNVQxaGxjY3kxNVkzcmJAY2x1c3RlcjAuZm9yaGhoYy5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
