apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: bzFleXdoOWg=
  CLOUDINARY_KEY: NzYyNzgxODgxMzMzMzI2
  CLOUDINARY_SECRET: KioqKioqKioqKg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM1p5WldSa2VUa3hNakFpTENKaElqb2lZMjF6WW1veGMzZzJNR3R0TlRNd2N6VmlZV0UwY2pZd09TSjkueExqRzNCSkVkdzVBSktIa2ZqanMyQQ==
  DB_URL: mongodb+srv://kuppireddyvenkateswarareddy69_db_user:rp5T1hlccy15Y3rb@cluster0.forhhhc.mongodb.net/?appName=Cluster0
