apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: bzFleXdoOWg=
  CLOUDINARY_KEY: ODI5MTE0NzU4ODYxNjY2
  CLOUDINARY_SECRET: S2lvcUtpb3FLaW9xS2c9PQ==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM1p5WldSa2VUa3hNakFpTENKaElqb2lZMjEwZDNNMmJ6UjVNREZzY3pKM2NYZzVPSEJ5ZFdKd2NTSjkuWnpvc3l2NjI0dFJZdzl0NVF3OF9kQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9rdXBwaXJlZGR5dmVua2F0ZXN3YXJhcmVkZHk2OV9kYl91c2VyOkt2cmVkZHk5MTIwQGNsdXN0ZXIwLmw2cGx2bWQubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
